### ISSUE TITLE
[Bug]: White Background Flash on Page Load  (v0.4.5)

### ISSUE THREAD

**Issue by ramonmalcolm10** [pacocoursey/next-themes#343]
### What happened?

After updating to next-theme v0.4.5, I am experiencing a white background flash on initial page load.

### Version

0.4.5

### What browsers are you seeing the problem on?

Chrome

**Comment by RobinGiel** [comment]
I can confirm this, after upgrading I'm now also getting this

**Comment by eposha** [comment]
The same issue

**Comment by 2803media** [comment]
same problem with Next.js 15.2.1, tailwindcss@3.4.17

**Comment by groveom** [comment]
Solved in https://github.com/pacocoursey/next-themes/pull/344

**Comment by Burotan** [comment]
To fix: 

1. Remove attribute="class" from ThemeProvider
2. Change @custom-variant dark (&:is(.dark *)); to @custom-variant dark (&:is([data-theme="dark"] *)); in css file

**Comment by fuma-nama** [comment]
Or you could downgrade to 0.4.4, which still works without the above issue

**Comment by yasseralsaidi** [comment]
same

**Comment by pacocoursey** [comment]
Fixed in 0.4.6

**Comment by fdcastel** [comment]
I'm using version `0.4.6` and still encountering this issue.

In a production build, reloading the page while in dark mode causes a white flash.

- Adding the following to the `<head>` section of `index.html` solved the problem.

    ```javascript
    <script>
      (function() {
        // Detect dark mode preference and set the class before Tailwind loads.
        // This avoids a flash of unstyled content (FOUC) when the page loads.
        try {
          var theme = localStorage.getItem('theme');
          var systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
          if (theme === 'dark' || (!theme && systemDark)) {
            document.documentElement.classList.add('dark');
          }
        } catch (e) {}
      })();
    </script>    
    ```
    
- For reference: project dependencies are 

    ```json
    "dependencies": {
      "@heroui/react": "^2.7.8",
      "@microsoft/signalr": "^8.0.7",
      "dayjs": "^1.11.13",
      "framer-motion": "^12.12.1",
      "next-themes": "^0.4.6",
      "react": "^18.3.1",
      "react-dom": "^18.3.1",
      "react-icons": "^5.5.0",
      "swr": "2.2.5"
    },
    ```

**Comment by groveom** [comment]
> I'm using version `0.4.6` and still encountering this issue.
> 
> In a production build, reloading the page while in dark mode causes a white flash.
> 
> * Adding the following to the `<head>` section of `index.html` solved the problem.
>   <script>
>     (function() {
>       // Detect dark mode preference and set the class before Tailwind loads.
>       // This avoids a flash of unstyled content (FOUC) when the page loads.
>       try {
>         var theme = localStorage.getItem('theme');
>         var systemDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
>         if (theme === 'dark' || (!theme && systemDark)) {
>           document.documentElement.classList.add('dark');
>         }
>       } catch (e) {}
>     })();
>   </script>
> * For reference: project dependencies are
>   "dependencies": {
>     "@heroui/react": "^2.7.8",
>     "@microsoft/signalr": "^8.0.7",
>     "dayjs": "^1.11.13",
>     "framer-motion": "^12.12.1",
>     "next-themes": "^0.4.6",
>     "react": "^18.3.1",
>     "react-dom": "^18.3.1",
>     "react-icons": "^5.5.0",
>     "swr": "2.2.5"
>   },

Can you show me the implementation of the package in your layout?

**Comment by fdcastel** [comment]
Sure! It's a straightforward application built with Vite, React, and HeroUI.

You can view the UI project [here](https://github.com/fdcastel/Deucalion/tree/master/src/ts/deucalion-ui).

The workaround can be found [here](https://github.com/fdcastel/Deucalion/blob/master/src/ts/deucalion-ui/index.html#L11-L23).

If the workaround is removed, the flash issue reappears.

Please let me know if you'd like me to run any additional tests or provide further information.

**Comment by groveom** [comment]
@fdcastel This issue comes from older versions?

**Comment by groveom** [comment]
@fdcastel Solved in https://github.com/pacocoursey/next-themes/pull/358
